"""empty message

Revision ID: 3bb273a35455
Revises: de0267afb429
Create Date: 2021-07-23 11:06:26.916990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb273a35455'
down_revision = 'de0267afb429'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('cat_cards')
    # ### end Alembic commands ###

    def downgrade():
            
        # ### commands auto generated by Alembic - please adjust! ###
        # op.create_table('cat_cards',
        # sa.Column('card_id', sa.INTEGER(), autoincrement=True, nullable=False),
        # sa.Column('card_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        # sa.Column('general_description', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.Column('upright_description', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.Column('reversed_description', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.Column('image_location', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.PrimaryKeyConstraint('card_id', name='cat_cards_pkey')
        # )
        op.drop_table('cat_cards')
        ### end Alembic commands ###
