"""empty message

Revision ID: 9196d6077bda
Revises: 55d828bc6816
Create Date: 2021-07-20 18:26:32.946033

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9196d6077bda'
down_revision = '55d828bc6816'
branch_labels = None
depends_on = None


def upgrade():
    #### commands auto generated by Alembic - please adjust! ###
    # op.create_table('layout',
    # sa.Column('layout_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.String(), nullable=False),
    # sa.PrimaryKeyConstraint('layout_id')
    # )
    # op.drop_table('cat_cards')
    # ### end Alembic commands ###


    def downgrade():
        #### commands auto generated by Alembic - please adjust! ###
        # op.create_table('cat_cards',
        # sa.Column('card_id', sa.INTEGER(), autoincrement=True, nullable=False),
        # sa.Column('card_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        # sa.Column('general_description', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.Column('upright_description', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.Column('reversed_description', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.Column('image_location', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.PrimaryKeyConstraint('card_id', name='cat_cards_pkey')
        # )
        op.drop_table('layout')
        # ### end Alembic commands ###
