"""empty message

Revision ID: de0267afb429
Revises: 9196d6077bda
Create Date: 2021-07-20 18:41:40.002866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de0267afb429'
down_revision = '9196d6077bda'
branch_labels = None
depends_on = None


def upgrade():
    #### commands auto generated by Alembic - please adjust! ###
    # op.create_table('layout',
    # sa.Column('layout_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('title', sa.String(), nullable=False),
    # sa.PrimaryKeyConstraint('layout_id')
    # )

    def downgrade():
        #### commands auto generated by Alembic - please adjust! ###
        # op.create_table('cat_cards',
        # sa.Column('card_id', sa.INTEGER(), autoincrement=True, nullable=False),
        # sa.Column('card_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
        # sa.Column('general_description', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.Column('upright_description', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.Column('reversed_description', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.Column('image_location', sa.TEXT(), autoincrement=False, nullable=True),
        # sa.PrimaryKeyConstraint('card_id', name='cat_cards_pkey')
        # )
        op.drop_table('layout')